version: '3.3'
services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; node dist/src/app.js'
    environment:
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    ports: 
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "qcrm-db-user"
      POSTGRES_PASSWORD: "db-password"
      POSTGRES_DB: "qcrm"
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080