version: '3.1'
services:
  web:
    image: cis-back
    command: sh -c "/wait && /sayhello"
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports: 
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "qcrm-db-user"
      POSTGRES_PASSWORD: "db-password"
      POSTGRES_DB: "qcrm"
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080