version: '3.7'
services:
  web:
    build: .
    environment:
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    ports: 
      - 8080:8080
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "qcrm-db-user"
      POSTGRES_PASSWORD: "db-password"
      POSTGRES_DB: "qcrm"
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080