version: 2.1
orbs:
  node: circleci/node@2.0.3
jobs:
  back-test:
    executor:
      name: node/default
      tag: '13.9'
    parameters:
      cache-version:
        default: v2
        type: string
    steps:
      - checkout
      - restore_cache:
          key: back-dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: back-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm test
  front-test:
    executor:
      name: node/default
      tag: '13.9'
    parameters:
      cache-version:
        default: v2
        type: string
    working_directory: ~/repo/deps/cis-front
    steps:
      - checkout:
          path: ~/repo
      - run: 
          command: cd ../../ && npm install && npm start
          background: true
      - restore_cache:
          key: front-dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: front-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          shell: /bin/sh
          command: |
            wget --retry-connrefused --waitretry=1 --read-timeout=40 --timeout=30 -t 10 http://localhost:8080/api/v1
            :
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - back-test
        - front-test