version: 2.1
orbs:
  node: circleci/node@2.0.3
jobs:
  back-test:
    executor:
      name: node/default
      tag: '13.9'
    parameters:
      cache-version:
        default: v2
        type: string
    steps:
      - checkout
      - restore_cache:
          key: back-dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: back-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm test
  front-test:
    executor:
      name: node/default
      tag: '13.9'
    parameters:
      cache-version:
        default: v2
        type: string
    steps:
      - checkout
      - run:
          name: "Pull submodules"
          command: |
            git submodule init
            git submodule update --remote
      - restore_cache:
          key: full-dependency-cache-{{ checksum "package-lock.json" }}-{{ checksum "./deps/cis-front/package-lock.json" }}
      - run: 
          name: "Build and start server"
          command: |
            npm install
            npm start
          background: true
      - run: 
          name: "Install packages of cis-front"
          command: |
            cd ./deps/cis-front
            npm install
      - save_cache:
          key: full-dependency-cache-{{ checksum "package-lock.json" }}-{{ checksum "./deps/cis-front/package-lock.json" }}
          paths:
            - ./node_modules
            - ./deps/cis-front/node_modules
      - run:
          name: "Waiting when server start listening"
          shell: /bin/sh
          command: |
            wget --retry-connrefused --waitretry=1 --read-timeout=40 --timeout=30 -t 10 http://localhost:8080/api/v1
            :
      - run:
          name: "Start testing of front-end"
          environment:
            SKIP_PREFLIGHT_CHECK: true # Skip checking deps for CRA
          command: |
            cd ./deps/cis-front
            npm test

workflows:
    build-and-test:
      jobs:
        - back-test
        - front-test