version: 2.1
orbs:
  node: circleci/node@2.0.3
jobs:
  back-test:
    executor:
      name: node/default
      tag: '13.9'
    parameters:
      cache-version:
        default: v2
        type: string
    steps:
      - checkout
      - restore_cache:
          key: back-dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: back-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm test
  front-test:
    executor:
      name: node/default
      tag: '13.9'
    parameters:
      cache-version:
        default: v2
        type: string
    steps:
      - checkout
      - restore_cache:
          key: back-dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - run:
          name: test
          command: npm start
          background: true
      - run: cd deps/cis-front
      - restore_cache:
          key: front-dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: front-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - back-test
        - front-test