version: 2.1
orbs:
  node: circleci/node@2.0.3
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '13'
    parameters:
      cache-version:
        default: v2
        type: string
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test