export enum Errors {
  UNKNOWN_ERROR = 1,
  PATH_NOT_FOUND,
  SERVICE_ERROR,
  REQUEST_VALIDATE_ERROR,
  INSERT_ENTITY_ERROR,
  UPDATE_ENTITY_ERROR,
  AUTH_USER_NOT_FOUND,
  REGISTER_USER_IS_EXIST,
  AUTH_WRONG_PASSWORD,
  FILE_UPLOAD_ERROR,
  UNKNOWN_PERMISSION_ID,
  NO_PERMISSION_FOR_RESOURCE,
}